### ISSUE TITLE
Suggest consider storing schema in http://www.openmobilealliance.org/tech/profiles/JSD

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/test2#2]
It may be worth considering storing the schema in the folder http://www.openmobilealliance.org/tech/profiles/JSD that is is for JSON schema definition packages.

**Comment by jpradocueva** [comment]
@jmudge please submit a PR to change the current URL. Thanks

**Comment by jmudge** [comment]
PR https://github.com/OpenMobileAlliance/test2/pull/4 has been submitted to address this.
